"""status column added in student profile

Revision ID: 1ccccecbfe68
Revises: d541f3c90e7c
Create Date: 2026-06-16 16:49:31.597024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccccecbfe68'
down_revision: Union[str, Sequence[str], None] = 'd541f3c90e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('status', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'status')
    # ### end Alembic commands ###
