"""create student_accounts model

Revision ID: 3c2c21cbf20d
Revises: 
Create Date: 2026-06-04 12:14:22.549244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2c21cbf20d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('student_type', sa.Enum('regular', 'deaf', name='studenttype'), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_accounts_id'), 'student_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_student_accounts_username'), 'student_accounts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_accounts_username'), table_name='student_accounts')
    op.drop_index(op.f('ix_student_accounts_id'), table_name='student_accounts')
    op.drop_table('student_accounts')
    # ### end Alembic commands ###
