"""added student_profile model, and relationship column in account model

Revision ID: 8e6f9a0d08be
Revises: ad58140477a1
Create Date: 2026-06-13 17:26:52.459559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6f9a0d08be'
down_revision: Union[str, Sequence[str], None] = 'ad58140477a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
