"""teacher profile table created

Revision ID: 98446007f2f3
Revises: 332acfa988b7
Create Date: 2026-06-16 22:09:58.013614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98446007f2f3'
down_revision: Union[str, Sequence[str], None] = '332acfa988b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_no', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index(op.f('ix_teacher_profiles_account_id'), 'teacher_profiles', ['account_id'], unique=True)
    op.create_index(op.f('ix_teacher_profiles_id'), 'teacher_profiles', ['id'], unique=False)
    op.alter_column('accounts', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('accounts', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('accounts', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_teacher_profiles_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_account_id'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    # ### end Alembic commands ###
