"""fixed Account Model

Revision ID: ad58140477a1
Revises: d65aa3d4be2f
Create Date: 2026-06-04 20:57:16.012082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad58140477a1'
down_revision: Union[str, Sequence[str], None] = 'd65aa3d4be2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_accounts_identifier'), table_name='accounts')
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.drop_column('accounts', 'password')
    op.drop_column('accounts', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('identifier', sa.VARCHAR(length=100), nullable=False))
    op.add_column('accounts', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.create_index(op.f('ix_accounts_identifier'), 'accounts', ['identifier'], unique=1)
    op.drop_column('accounts', 'hashed_password')
    op.drop_column('accounts', 'email')
    op.drop_column('accounts', 'username')
    # ### end Alembic commands ###
