"""Student Profile table create

Revision ID: d541f3c90e7c
Revises: 8e6f9a0d08be
Create Date: 2026-06-14 16:57:41.586070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd541f3c90e7c'
down_revision: Union[str, Sequence[str], None] = '8e6f9a0d08be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('student_type', sa.Enum('regular', 'HI', name='studenttype'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('guardians_name', sa.String(), nullable=True),
    sa.Column('guardians_contact_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_account_id'), 'student_profiles', ['account_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_account_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
